# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: required

matrix:
  # These are all the build jobs. Adjust as necessary.
  include:
    # Android
    - env: TARGET=arm-linux-androideabi DISABLE_TESTS=1 FEATURES=--all-features
    - env: TARGET=armv7-linux-androideabi DISABLE_TESTS=1 FEATURES=--all-features
    - env: TARGET=i686-linux-android DISABLE_TESTS=1 FEATURES=--all-features

    # Linux
    - env: TARGET=aarch64-unknown-linux-gnu FEATURES=--all-features
    - env: TARGET=arm-unknown-linux-gnueabi FEATURES=--all-features
    - env: TARGET=armv7-unknown-linux-gnueabihf FEATURES=--all-features
    - env: TARGET=i686-unknown-linux-gnu FEATURES=--all-features
    - env: TARGET=i686-unknown-linux-musl FEATURES=--all-features
    - env: TARGET=x86_64-unknown-linux-gnu FEATURES=--all-features
    - env: TARGET=x86_64-unknown-linux-musl FEATURES=--all-features

    # OSX
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin FEATURES=--all-features
      os: osx

    # *BSD
    - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1 FEATURES=--all-features
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1 FEATURES=--all-features
    - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1 FEATURES=--all-features
      rust: nightly

    # Solaris/illumos
    - env: TARGET=sparcv9-sun-solaris DISABLE_TESTS=1 FEATURES=--all-features
    - env: TARGET=x86_64-sun-solaris DISABLE_TESTS=1 FEATURES=--all-features

    # Windows
    - env: TARGET=x86_64-pc-windows-gnu
    - env: TARGET=x86_64-pc-windows-msvc DISABLE_TESTS=1
      os: windows

before_install:
  - set -e
  - rustup self update

install:
  - cargo install cross
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
